language: ruby
sudo: true
rvm:
  - 2.2.2 # oldest version supported by Rails 5
  - 2.3.1 # latest release
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - MAPNIK_VERSION="2.3"
  matrix:
    - RAILS_VERSION=4.2.7
      RDF_VERSION=1.99.1
    - RAILS_VERSION=5.0.0
      RDF_VERSION=2.1.0
before_install:
 - sudo apt-add-repository --yes ppa:mapnik/nightly-${MAPNIK_VERSION}
 - sudo apt-get update -y
install:
 - sudo apt-get -y install wget build-essential make libmapnik=${MAPNIK_VERSION}* mapnik-utils=${MAPNIK_VERSION}* libmapnik-dev=${MAPNIK_VERSION}* mapnik-input-plugin*=${MAPNIK_VERSION}*
before_script:
  - jdk_switcher use oraclejdk8
  - gdalinfo --version
  - gem install bundler -v 1.12.3
  - bundle install
services:
  - redis-server
addons:
  apt:
    packages:
    - gdal-bin
