language: ruby
cache: bundler
sudo: true
rvm:
  - 2.3.1 # latest release
jdk:
  - oraclejdk8
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - MAPNIK_VERSION="2.3"
  matrix:
    - RAILS_VERSION=4.2.7.1
      RDF_VERSION=1.99.1
    - RAILS_VERSION=5.0.0.1
      RDF_VERSION=2.1.0
before_install:
 - sudo apt-add-repository --yes ppa:mapnik/nightly-${MAPNIK_VERSION}
 - sudo apt-get update -y
 - sudo apt-get -y install libmapnik=${MAPNIK_VERSION}* mapnik-utils=${MAPNIK_VERSION}* libmapnik-dev=${MAPNIK_VERSION}* mapnik-input-plugin*=${MAPNIK_VERSION}*
install: bundle install --jobs=3 --retry=3
before_script:
  - gdalinfo --version
services:
  - redis-server
addons:
  apt:
    packages:
    - gdal-bin
