language: ruby
sudo: true
rvm:
  - 2.3.0
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - MAPNIK_VERSION="2.3"
before_install:
 - sudo apt-add-repository --yes ppa:mapnik/nightly-${MAPNIK_VERSION}
 - sudo apt-get update -y
install:
 - sudo apt-get -y install wget build-essential make libmapnik=${MAPNIK_VERSION}* mapnik-utils=${MAPNIK_VERSION}* libmapnik-dev=${MAPNIK_VERSION}* mapnik-input-plugin*=${MAPNIK_VERSION}*
before_script:
  - jdk_switcher use oraclejdk8
  - gdalinfo --version
  - gem install bundler -v 1.12.3
  - bundle install
services:
  - redis-server
addons:
  apt:
    packages:
    - gdal-bin
